[PARSER]
    Name         docker_json
    Format       json
    Time_Key     time
    Time_Format  %Y-%m-%dT%H:%M:%S.%L
    Time_Keep    On

[PARSER]
    Name         python_log
    Format       regex
    Regex        ^(?<timestamp>[^ ]+ [^ ]+) (?<level>[A-Z]+) +(?<message>.*)$
    Time_Key     timestamp
    Time_Format  %Y-%m-%d %H:%M:%S,%
